### ISSUE TITLE
FIFOQueue is closed and has insufficient elements

### ISSUE THREAD

**Issue by efang96** [MichiganCOG/M-PACT#7]
I'm running into a OutOfRange error when running the following command. The error traceback is listed at the end.

```
python train.py --model c3d --numGpus 2 --dataset caltrain --load 0 --inputDims 10 --outputDims 4 --seqLength 1 --size 112  --expName example_1 --numClips 1 --clipLength 10 --clipOffset random --numVids 385 --split 1 --wd 0.0005 --lr 0.0001 --nEpochs 30 --baseDataPath data --fName trainlist --saveFreq 1 --verbose 1 --batchSize 10
```

I'm wondering why this might be, because I'm able to run training commands for the same dataset using resnet50 + LSTM and I3D. FYI this also fails when trying to train TSN. Is there some requirement on the data (such as minimum number of frames, resolutions, etc.) that C3D and TSN impose? I've seen online that this can usually be caused by incorrect paths or corrupt files but I'm confident both are correct as my other commands are working. Memory / GPU are also not issue, using a very beefy EC2 instance. Any help is greatly appreciated, thanks!

Here are the *working* commands:

```
# resnet50 + lstm on caltrain
python train.py  --model resnet  --dataset caltrain  --numGpus 2  --load 0  --size 224  --inputDims 10  --outputDims 4  --seqLength 10  --dropoutRate 0.5  --expName example_1  --numVids 385  --lr 0.01  --nEpochs 30  --baseDataPath data  --fName trainlist  --optChoice gd --batchSize 1
python test.py --model resnet --dataset caltrain --loadedDataset caltrain --train 0 --load 1 --inputDims 10 --outputDims 4 --seqLength 10 --size 224 --expName example_1 --numVids 40 --split 1 --baseDataPath data --fName testlist --freeze 1

# i3d on caltrain
python train.py --model i3d --inputDims 10 --outputDims 4 --dataset caltrain --load 0 --expName example_1 --numVids 385 --fName trainlist --seqLength 1 --size 224 --numGpus 2 --train 1 --split 1 --wd 0.0 --lr 0.01 --nEpochs 30 --baseDataPath data --saveFreq 1 --dropoutRate 0.5 --gradClipValue 100.0 --optChoice adam --batchSize 16
python test.py --model i3d --numGpus 1 --dataset caltrain --loadedDataset caltrain --train 0 --load 1 --inputDims 10 --outputDims 4 --seqLength 1 --size 224  --expName example_1 --numVids 40 --split 1 --baseDataPath data --fName testlist --verbose 1
```

Here is the error traceback:

```
Traceback (most recent call last):
  File "train.py", line 700, in <module>
    preproc_debugging   = args.preprocDebugging)
  File "train.py", line 525, in train
    learning_rate, model.get_track_variables()])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_my_scope/fifo_queue' is closed and has insufficient elements (requested 20, current size 0)
         [[Node: my_scope/fifo_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32, DT_STRING, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](my_scope/fifo_queue, my_scope/fifo_queue_DequeueMany/n)]]

Caused by op u'my_scope/fifo_queue_DequeueMany', defined at:
  File "train.py", line 700, in <module>
    preproc_debugging   = args.preprocDebugging)
  File "train.py", line 333, in train
    input_data_tensor, labels_tensor, names_tensor = load_dataset(model, num_gpus, batch_size, output_dims, input_dims, seq_length, size, data_path, dataset, istraining, clip_length, video_offset, clip_offset, num_clips, clip_stride, video_step, preproc_debugging, shuffle_seed, verbose)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 71, in load_dataset
    input_data_tensor, labels_tensor, names_tensor, video_step_tensor, alpha_tensor = clip_q.dequeue_many(num_gpus*batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 483, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_1_my_scope/fifo_queue' is closed and has insufficient elements (requested 20, current size 0)
         [[Node: my_scope/fifo_queue_DequeueMany = QueueDequeueManyV2[component_types=[DT_FLOAT, DT_INT32, DT_STRING, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](my_scope/fifo_queue, my_scope/fifo_queue_DequeueMany/n)]]
```

**Comment by ehofesmann** [comment]
Can you try to rerun the system with `--preprocDebugging 1` and post the error traceback?

**Comment by efang96** [comment]
Thanks for the response, it seems that it expects a clip length of 16. Here is the traceback.

```
Traceback (most recent call last):
  File "train.py", line 700, in <module>
    preproc_debugging   = args.preprocDebugging)
  File "train.py", line 525, in train
    learning_rate, model.get_track_variables()])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [10,128,171,3] vs. [16,128,171,3]
         [[Node: my_scope/map_1/while/sub_1 = Sub[T=DT_FLOAT, _class=["loc:@my_sc...yScatterV3"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](my_scope/map_1/while/map/TensorArrayStack/TensorArrayGatherV3, my_scope/map_1/while/sub_1/y)]]
         [[Node: my_scope/map_1/TensorArrayStack/TensorArrayGatherV3/_155 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_146_my_scope/map_1/TensorArrayStack/TensorArrayGatherV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]

Caused by op u'my_scope/map_1/while/sub_1', defined at:
  File "train.py", line 700, in <module>
    preproc_debugging   = args.preprocDebugging)
  File "train.py", line 333, in train
    input_data_tensor, labels_tensor, names_tensor = load_dataset(model, num_gpus, batch_size, output_dims, input_dims, seq_length, size, data_path, dataset, istraining, clip_length, video_offset, clip_offset, num_clips, clip_stride, video_step, preproc_debugging, shuffle_seed, verbose)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 52, in load_dataset
    input_data_tensor, labels_tensor, names_tensor, video_step_tensor, alpha_tensor = _load_video(model, output_dims, input_dims, seq_length, size, base_data_path, dataset, istraining, clip_length, video_offset, clip_offset, num_clips, clip_stride, tfrecord_file_queue, video_step)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 154, in _load_video
    clips, dtype=tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 423, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 413, in compute
    packed_fn_values = fn(packed_values)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 153, in <lambda>
    clips_tensor = tf.map_fn(lambda clip: model.preprocess_tfrecords(clip, tf.shape(clip)[0], height, width,channel, input_dims, output_dims, seq_length, size, label, istraining, video_step),
  File "/mnt/user-home/M-PACT/models/c3d/c3d_model.py", line 173, in preprocess_tfrecords
    return preprocess(input_data_tensor, frames, height, width, channel, input_dims, output_dims, seq_length, size, label, istraining, self.input_alpha)
  File "/mnt/user-home/M-PACT/models/c3d/default_preprocessing.py", line 95, in preprocess
    input_data_tensor = input_data_tensor - _mean_image[...,::-1].tolist()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 979, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 8009, in sub
    "Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [10,128,171,3] vs. [16,128,171,3]
         [[Node: my_scope/map_1/while/sub_1 = Sub[T=DT_FLOAT, _class=["loc:@my_sc...yScatterV3"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](my_scope/map_1/while/map/TensorArrayStack/TensorArrayGatherV3, my_scope/map_1/while/sub_1/y)]]
         [[Node: my_scope/map_1/TensorArrayStack/TensorArrayGatherV3/_155 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_146_my_scope/map_1/TensorArrayStack/TensorArrayGatherV3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]
```

Thus I changed the command to have `--inputDims 16` and `--clipLength 16`. Below is the command.

```
python train.py --model c3d --numGpus 2 --dataset caltrain --load 0 --inputDims 16 --outputDims 4 --seqLength 1 --size 112  --expName example_1 --numClips 1 --clipLength 16 --clipOffset random --numVids 385 --split 1 --wd 0.0005 --lr 0.0001 --nEpochs 30 --baseDataPath data --fName trainlist --saveFreq 1 --verbose 1 --batchSize 1 --preprocDebugging 1
```

However, this produces a different error:
```
2019-02-19 17:35:23.417519: F tensorflow/stream_executor/cuda/cuda_dnn.cc:521] could not convert BatchDescriptor {count: 0 feature_map_count: 64 spatial: 16 112 112  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX} to cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)
```

**Comment by ehofesmann** [comment]
It looks like this issue may occur when you don't have the right number of channels. Are you using RGB videos? Which versions of CUDA and Cudnn are you using?

Also try rerunning the command without `preprocDebugging` and using only 1 GPU.

**Comment by efang96** [comment]
Rerunning with 1 GPU fixed it! Thanks a lot for the help. Any reason why multi-gpu is complaining?

**Comment by efang96** [comment]
When running 
```
python train.py --model tsn --dataset caltrain --numGpus 1 --load 0 --inputDims 3 --outputDims 4 --batchSize 1 --seqLength 3 --size 224  --expName example_1 --numVids 385 --lr 0.001 --wd 0.0005 --nEpochs 40 --split 1 --baseDataPath data --fName trainlist --gradClipVal 20 --optChoice momentum --preprocDebugging 1
```

the command deterministically fails on step 27 with the following error:

```
Traceback (most recent call last):
  File "train.py", line 700, in <module>
    preproc_debugging   = args.preprocDebugging)
  File "train.py", line 525, in train
    learning_rate, model.get_track_variables()])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= 0
         [[Node: my_scope/map/while/random_uniform = RandomUniformInt[T=DT_INT64, Tout=DT_INT32, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](my_scope/map/while/random_uniform_3/shape, my_scope/map/while/mul_1/_971, my_scope/map/while/sub_1/_973)]]
         [[Node: my_scope/map/while/strided_slice_4/_1005 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_818_my_scope/map/while/strided_slice_4", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^my_scope/map/while/strided_slice_4/_1004)]]

Caused by op u'my_scope/map/while/random_uniform', defined at:
  File "train.py", line 700, in <module>
    preproc_debugging   = args.preprocDebugging)
  File "train.py", line 333, in train
    input_data_tensor, labels_tensor, names_tensor = load_dataset(model, num_gpus, batch_size, output_dims, input_dims, seq_length, size, data_path, dataset, istraining, clip_length, video_offset, clip_offset, num_clips, clip_stride, video_step, preproc_debugging, shuffle_seed, verbose)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 52, in load_dataset
    input_data_tensor, labels_tensor, names_tensor, video_step_tensor, alpha_tensor = _load_video(model, output_dims, input_dims, seq_length, size, base_data_path, dataset, istraining, clip_length, video_offset, clip_offset, num_clips, clip_stride, tfrecord_file_queue, video_step)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 154, in _load_video
    clips, dtype=tf.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 423, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 413, in compute
    packed_fn_values = fn(packed_values)
  File "/mnt/user-home/M-PACT/utils/load_dataset_tfrecords.py", line 153, in <lambda>
    clips_tensor = tf.map_fn(lambda clip: model.preprocess_tfrecords(clip, tf.shape(clip)[0], height, width,channel, input_dims, output_dims, seq_length, size, label, istraining, video_step),
  File "/mnt/user-home/M-PACT/models/tsn/tsn_model.py", line 209, in preprocess_tfrecords
    return preprocess(input_data_tensor, frames, height, width, channel, input_dims, output_dims, seq_length, size, label, istraining, video_step, self.num_segs, self.input_alpha)
  File "/mnt/user-home/M-PACT/models/tsn/default_preprocessing.py", line 112, in preprocess
    random_extract_index = tf.random_uniform(dtype=tf.int32, minval=seg * segment_length, maxval= (seg+1)*segment_length - snippet_length, shape=np.asarray([1]))[0]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/random_ops.py", line 240, in random_uniform
    shape, minval, maxval, seed=seed1, seed2=seed2, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_random_ops.py", line 764, in random_uniform_int
    seed=seed, seed2=seed2, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Need minval < maxval, got 0 >= 0
         [[Node: my_scope/map/while/random_uniform = RandomUniformInt[T=DT_INT64, Tout=DT_INT32, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](my_scope/map/while/random_uniform_3/shape, my_scope/map/while/mul_1/_971, my_scope/map/while/sub_1/_973)]]
         [[Node: my_scope/map/while/strided_slice_4/_1005 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_818_my_scope/map/while/strided_slice_4", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^my_scope/map/while/strided_slice_4/_1004)]]
```

**Comment by ehofesmann** [comment]
For C3D: 
```
python train.py --model c3d --numGpus 2 --dataset caltrain --load 0 --inputDims 16 --outputDims 4 --seqLength 1 --size 112  --expName example_1 --numClips 1 --clipLength 16 --clipOffset random --numVids 385 --split 1 --wd 0.0005 --lr 0.0001 --nEpochs 30 --baseDataPath data --fName trainlist --saveFreq 1 --verbose 1 --batchSize 2
``` 
Remove preprocDebugging and have batchSize be at least numGpus


For TSN: The problem is something that should have been fixed in the commit from ~5 days ago. Try to pull and run it again.

**Comment by efang96** [comment]
Awesome, thanks so much for the help. Really appreciate it!
